[project]
name = "assisted-service-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "assisted-service-client>=2.41.0.post3",
    "mcp[cli]>=1.9.0",
    "netaddr>=1.3.0",
    "requests>=2.32.3",
    "retry>=0.9.2",
]
