---
apiVersion: v1
kind: Template
metadata:
  name: assisted-service-mcp
parameters:
  - name: IMAGE
    value: quay.io/carbonin/assisted-service-mcp
  - name: IMAGE_TAG
    value: latest
  - name: INVENTORY_URL
    value: "https://api.openshift.com/api/assisted-install/v2"
  - name: SSO_URL
    value: "https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token"
  - name: PULL_SECRET_URL
    value: "https://api.openshift.com/api/accounts_mgmt/v1/access_token"
  - name: CLIENT_DEBUG
    value: "False"
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: assisted-service-mcp
    name: assisted-service-mcp
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: assisted-service-mcp
    template:
      metadata:
        labels:
          app: assisted-service-mcp
      spec:
        containers:
        - name: assisted-service-mcp
          image: ${IMAGE}:${IMAGE_TAG}
          ports:
          - containerPort: 8000
            protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
          env:
          - name: INVENTORY_URL
            value: ${INVENTORY_URL}
          - name: SSO_URL
            value: ${SSO_URL}
          - name: PULL_SECRET_URL
            value: ${PULL_SECRET_URL}
          - name: CLIENT_DEBUG
            value: ${CLIENT_DEBUG}
- apiVersion: v1
  kind: Service
  metadata:
    name: assisted-service-mcp
    labels:
      app: assisted-service-mcp
  spec:
    selector:
      app: assisted-service-mcp
    ports:
      - protocol: TCP
        port: 8000
        targetPort: 8000

